### ISSUE TITLE
Thin3D Clear() uses inconsistent color component order

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/native#254]
OpenGL:
Uint32ToFloat4(colorval, col);
glClearColor(col[0], col[1], col[2], col[3]);

Direct3D 9:
(D3DCOLOR)colorval

As such, OpenGL uses 0xAABBGGRR and Direct3D 9 uses 0xAARRGGBB.

Incidentally, PPSSPP seems to assume 0xAARRGGBB (which is probably the clearer one to type.)  This means that in OpenGL, if you do things like mashing F11 or etc., you'll see a brown background color.

dc.GetThin3DContext()->Clear(T3DClear::COLOR | T3DClear::DEPTH | T3DClear::STENCIL, 0xff224477, 0.0, 0);

It's clearly meant to be a bluish color, rather than a redish one, which implies that OpenGL should be color swapped.  But, I'm not sure which color order is best.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks, I chose the OpenGL ordering. Done :)
