### ISSUE TITLE
atlastool does not need Glew

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/native#278]
Trying to compile atlastool on ARM, and it fails because native/base/timeutil.cpp includes glew header (by gl_state.h --> gfx/gl_common.h)

```
[  3%] Building CXX object base/CMakeFiles/base.dir/timeutil.cpp.o
In file included from /«BUILDDIR»/ppsspp-qt-1.0.1+r63.f46.n1198.l1596.a159.t83~21~ubuntu14.04.1/native/tools/../gfx_es2/gl_state.h:6:0,
                 from /«BUILDDIR»/ppsspp-qt-1.0.1+r63.f46.n1198.l1596.a159.t83~21~ubuntu14.04.1/native/base/timeutil.cpp:6:
/«BUILDDIR»/ppsspp-qt-1.0.1+r63.f46.n1198.l1596.a159.t83~21~ubuntu14.04.1/native/tools/../gfx/gl_common.h:14:21: fatal error: GL/glew.h: No such file or directory
 #include <GL/glew.h>
                     ^
compilation terminated.
```

https://launchpadlibrarian.net/209838887/buildlog_ubuntu-trusty-armhf.ppsspp-qt_1.0.1%2Br63.f46.n1198.l1596.a159.t83~21~ubuntu14.04.1_BUILDING.txt.gz

native/base/timeutil.cpp:

```
// For NV time functions. Ugly!
#include "gfx_es2/gl_state.h"
```

atlastool is not even linked to Glew.

**Comment by hrydgard** [comment]
native is no longer an active project, it was merged into PPSSPP. Closing issue.
